CREATE TABLE covid_deaths.CovidDeaths(
iso_code	varchar(10),
continent varchar(30),
location varchar(50),
date DATE,
population bigint,
total_cases bigint,
new_cases bigint,
new_cases_smoothed numeric,
total_deaths bigint,
new_deaths bigint,
new_deaths_smoothed numeric,
total_cases_per_million numeric, 
new_cases_per_million numeric,
new_cases_smoothed_per_million numeric,
total_deaths_per_million numeric,
new_deaths_per_million numeric,
new_deaths_smoothed_per_million numeric,
reproduction_rate numeric,
icu_patients bigint,
icu_patients_per_million numeric,
hosp_patients bigint,
hosp_patients_per_million numeric,
weekly_icu_admissions numeric,
weekly_icu_admissions_per_million numeric,
weekly_hosp_admissions numeric,
weekly_hosp_admissions_per_million numeric
);


CREATE TABLE covid_deaths.CovidVacs(
iso_code varchar(10),
continent varchar(20),
location varchar(50),
date DATE,
new_tests BIGINT,
total_tests BIGINT,
total_tests_per_thousand numeric,
new_tests_per_thousand numeric,
new_tests_smoothed BIGINT,
new_tests_smoothed_per_thousand numeric,
positive_rate numeric,
tests_per_case numeric,
tests_units varchar(50),
total_vaccinations BIGINT,
people_vaccinated BIGINT,
people_fully_vaccinated BIGINT,
new_vaccinations BIGINT,
new_vaccinations_smoothed BIGINT,
total_vaccinations_per_hundred numeric,
people_vaccinated_per_hundred numeric,
people_fully_vaccinated_per_hundred numeric,
new_vaccinations_smoothed_per_million BIGINT,
stringency_index numeric,
population_density numeric,
median_age numeric,
aged_65_older numeric,
aged_70_older numeric,
gdp_per_capita numeric,
extreme_poverty numeric,
cardiovasc_death_rate numeric,
diabetes_prevalence numeric,
female_smokers numeric,
male_smokers numeric,
handwashing_facilities numeric,
hospital_beds_per_thousand numeric,
life_expectancy numeric,
human_development_index numeric
);

